export interface JournalPrompt {
  text: string;
  attribution?: string;
}

// A mix of direct prompts and short quotes to nudge someone who's staring
// at a blank page — shown one at a time above the composer, shuffle-able.
// Two layers: original prompts written for this app (grouped by tone/theme,
// no attribution risk), and real quotes (grouped by source — literary,
// screen/game, anime, sports, etc.) sourced from a curated reference list
// (public/quotes_and_journal_prompts_full.md) and merged in with exact/near
// duplicates against the original set removed. Entries marked "paraphrased"
// in their attribution reflect a well-known sentiment rather than confirmed
// word-for-word dialogue — kept as marked rather than presented as exact.
export const JOURNAL_PROMPTS: JournalPrompt[] = [
  // Basic journaling questions
  { text: "How are you feeling right now?" },
  { text: "What's on your mind?" },
  { text: "What happened today?" },
  { text: "What's one word for today?" },
  { text: "What do you need right now?" },
  { text: "What's something you want to let go of?" },
  { text: "What's your intention for tomorrow?" },
  { text: "How did you sleep last night?" },
  { text: "What's something you're thinking about?" },
  { text: "What was the best part of your day?" },
  { text: "What was the hardest part of your day?" },
  { text: "What's something simple that made today better?" },

  // Plain, everyday
  { text: "What's the detail of what you accomplished today?" },
  { text: "What made you feel this way today?" },
  { text: "What made you feel excited today?" },
  { text: "What made you feel burned out today?" },
  { text: "What's one small thing that went right today?" },
  { text: "What are you looking forward to?" },
  { text: "What's something you'd like to remember about today?" },
  { text: "What's weighing on you right now?" },
  { text: "Who or what are you grateful for today?" },
  { text: "What's something you're proud of from today, even if it's small?" },
  { text: "What surprised you today?" },
  { text: "What's something you avoided today?" },
  { text: "How did you take care of yourself today?" },
  { text: "What conversation from today is still on your mind?" },
  { text: "What's something you learned about yourself today?" },
  { text: "What did you do today just for you?" },
  { text: "What's one thing you'd do differently if you could redo today?" },

  // More thoughtful / intellectual
  { text: "What belief do you hold today that you didn't a year ago?" },
  { text: "What's something you understand better now than you used to?" },
  { text: "What assumption did today quietly prove wrong?" },
  { text: "What would you tell yourself from exactly one year ago?" },
  { text: "What's a question about your own life you've been avoiding?" },
  { text: "If today were a chapter title in your autobiography, what would it be?" },
  { text: "What's a small discomfort you leaned into today instead of avoiding?" },
  { text: "What did today teach you that a textbook couldn't?" },
  { text: "What's something you did today purely out of habit — was it worth keeping?" },
  { text: "What's a belief you're still not sure you're allowed to have?" },
  { text: "If you could subtract one hour from today and add it to yesterday, would you?" },
  { text: "What's something you know intellectually but haven't fully accepted emotionally?" },
  { text: "What version of yourself were you performing today, if any?" },
  { text: "What's a contradiction you're currently living with?" },
  { text: "If today's choices were a data point, what pattern would they add to?" },
  { text: "What would you need to believe to feel differently about today?" },
  { text: "What's the smallest true thing you can say about today?" },
  { text: "If someone studied only today, what would they wrongly conclude about your life?" },

  // Random / fun
  { text: "If today had a soundtrack, what's the one song stuck in your head?" },
  { text: "What's the weirdest thing that happened today?" },
  { text: "Describe today using exactly three words." },
  { text: "What snack (or meal) saved today?" },
  { text: "If today were a weather forecast, what would it say?" },
  { text: "What's a completely useless fact you know, and why do you still know it?" },
  { text: "If your day were a movie genre, which one, and why?" },
  { text: "What made you laugh today, even just a little?" },
  { text: "If you could replay one hour from today, which one would you pick?" },
  { text: "If today were a flavor, what would it taste like?" },
  { text: "What's a smell that instantly time-traveled you somewhere today?" },
  { text: "If today had a warning label, what would it say?" },
  { text: "What's the most chaotic five minutes of your day?" },
  { text: "If your energy today were a battery percentage, what was it at 3pm?" },
  { text: "What's a word you overused today, out loud or in your head?" },
  { text: "If today were a plant, what kind would it be and why?" },
  { text: "What's the dumbest thing you thought about for way too long today?" },
  { text: "If today came with a soundtrack cue, what instrument would it be?" },
  { text: "What's one thing today that made zero sense?" },
  { text: "If you had to sell today on a shopping channel, what's your pitch?" },
  { text: "What color was today, and why?" },

  // Oddly specific / niche
  { text: "What's a smell that took you somewhere else today?" },
  { text: "If your day had a one-star review, what would it complain about?" },
  { text: "What's a rule — even a tiny one — you broke today?" },
  { text: "Name a sound from today you could pick out blindfolded." },
  { text: "What almost happened today, but didn't?" },
  { text: "What's something you did today your childhood self would be baffled by?" },
  { text: "What's the most 'you' thing you did today?" },
  { text: "Name a texture that stuck with you today." },
  { text: "What's something you almost said out loud but didn't?" },
  { text: "What's a tiny rebellion you committed today?" },
  { text: "What's something you only noticed because you were paying attention?" },
  { text: "What's a decision today you made in under five seconds?" },
  { text: "What object did you touch the most today, and what does that say?" },
  { text: "What's a habit you almost broke today but didn't?" },
  { text: "If today left a stain, what color would it be?" },

  // Pop-culture flavored
  { text: "If today were an episode title, what would it be called?" },
  { text: "Which sitcom character's energy did you have today?" },
  { text: "If you had a training montage today, what song would play?" },
  { text: "What villain-origin-story moment did today almost give you?" },
  { text: "Which fictional universe would today's events fit into best?" },
  { text: "If you had a superhero power today, what small problem would you have used it on?" },
  { text: "What's the meme that best sums up today?" },
  { text: "If today were a video game level, what was the boss fight?" },
  { text: "Which fictional character would've handled today better than you?" },
  { text: "What's a plot-armor moment from today — something that should've gone wrong but didn't?" },
  { text: "If today unlocked an achievement, what would it be called?" },
  { text: "If today were a season finale cliffhanger, what question got left unanswered?" },
  { text: "What's the opening line if today were a true-crime documentary?" },
  { text: "If today were a reality TV confessional, what would you say to the camera?" },
  { text: "Which fictional sidekick would've had the most commentary on your day?" },

  // Video games & interactive worlds
  { text: "If today were a Skyrim quest, what would the objective marker say?" },
  { text: "What today would count as taking an arrow in the knee?" },
  { text: "If today were a Disco Elysium skill check, which skill would've failed you?" },
  { text: "What internal voice argued with you the loudest today?" },
  { text: "If today were a GTA wanted level, how many stars would you be at right now?" },
  { text: "What's the side quest you got distracted by instead of today's main story?" },
  { text: "If today had a loading-screen tip, what would it say?" },
  { text: "What would your character sheet's 'notable trait' be after today?" },
  { text: "If today were a save file, what would you name the checkpoint?" },
  { text: "What's a debuff you were clearly under today?" },

  // Movies — MCU, DC & beyond
  { text: "If today were an MCU post-credits scene, what's the twist?" },
  { text: "Which superhero's day off did today resemble most?" },
  { text: "If today were a Batman origin-story beat, what happened in the alley?" },
  { text: "What was your 'I am inevitable' moment today — the thing you couldn't stop?" },
  { text: "Which villain monologue best explains your mood today?" },
  { text: "If today needed a post-credits scene, what would it tease?" },
  { text: "What's the training-montage moment from today?" },
  { text: "If today were a movie trailer, what's the one line that would sell it?" },
  { text: "What's the plot hole in today that nobody's going to question?" },

  // From the pitch — football flavored
  { text: "If today were a match, what's the final scoreline?" },
  { text: "What was your Messi moment today — small, quiet, but decisive?" },
  { text: "What was your Ronaldo moment today — loud, unmissable, celebrated?" },
  { text: "If today went to penalties, who would you trust to take the kick?" },
  { text: "What's the stoppage-time goal of your day — the thing that saved it at the last second?" },
  { text: "If today were a post-match interview, what's the one line you'd give reporters?" },
  { text: "What red card would you show today, if you could?" },
  { text: "If your day were a highlight reel, what's the one clip everyone would replay?" },

  // More mainstream games
  { text: "If today were a Dark Souls boss fight, how many tries did it take?" },
  { text: "What was today's 'Praise the Sun' moment — a small win worth celebrating?" },
  { text: "If today were a Zelda dungeon, what was the boss key you needed?" },
  { text: "What's the crafting recipe for today — what ingredients made it what it was?" },
  { text: "If today were a Portal test chamber, what was the trick you didn't see coming?" },
  { text: "What quest marker popped up out of nowhere today?" },
  { text: "If today were an RPG dialogue tree, which option did you almost pick but didn't?" },
  { text: "What's the respawn point you'd set today, if you could redo the rest?" },
  { text: "If today were a battle royale, what round did you get eliminated in?" },
  { text: "What's the easter egg from today — something small only you noticed?" },
  { text: "If today were an open-world map, what was still fogged over by the end?" },
  { text: "What NPC-brained moment did you have today — repeating the same line on a loop?" },

  // More movies
  { text: "If today were a Star Wars scene, were you closer to the light side or the dark side?" },
  { text: "What was your 'carrying the ring' moment today — the thing you couldn't put down?" },
  { text: "If today were a heist movie, what was the plan that almost went wrong?" },
  { text: "What's the twist ending if today were a thriller?" },
  { text: "If today were narrated like a nature documentary, what would the narrator say about you?" },
  { text: "What's the one scene from today you'd cut in the edit?" },
  { text: "If today were a Pixar movie, what's the emotional gut-punch moment?" },
  { text: "What's the soundtrack-swell moment from today — when it would've felt cinematic?" },
  { text: "If today were a courtroom drama, what would you plead guilty to?" },
  { text: "What's the sequel hook from today — something left unresolved?" },
  { text: "If today got a director's cut, what deleted scene would you add back in?" },

  // Celebrity-flavored
  { text: "Whose work ethic did today's grind remind you of?" },
  { text: "If a camera crew followed you today for a documentary, what would the trailer tease?" },
  { text: "What's the red-carpet-ready moment from today, if any?" },
  { text: "If you had to give an acceptance speech for today, who would you thank first?" },
  { text: "What's the comeback story arc your day is quietly building toward?" },
  { text: "If today were a magazine cover, what's the headline?" },

  // Anime & more games
  { text: "If today were a Jujutsu Kaisen domain expansion, what would yours be called?" },
  { text: "What was your Gojo-tier flex moment today, however small?" },
  { text: "If today were a One Piece arc, what island did you wash up on?" },
  { text: "What's the bounty you'd put on today's chaos?" },
  { text: "If today leveled you up like Solo Leveling, what stat went up?" },
  { text: "What was your 'it's over 9000' moment today — something that spiked out of nowhere?" },
  { text: "If today were a Pokémon battle, what move did you use, and was it super effective?" },
  { text: "What starter would today's mood evolve into?" },
  { text: "If today were a Mass Effect dialogue wheel, which option did you pick — paragon or renegade?" },
  { text: "What's the loyalty mission you completed for someone today?" },

  // More movies — Troy & Mission Impossible
  { text: "If today were a Mission: Impossible briefing, what was your mission, should you have chosen to accept it?" },
  { text: "What self-destructed after five seconds today, metaphorically speaking?" },
  { text: "If today were an epic like Troy, what would the opening narration say about you?" },
  { text: "What's the thing you'd want people to remember about today, years from now?" },

  // Niche references
  { text: "If today needed a skill check like in Disco Elysium, what would you have rolled for and failed?" },
  { text: "What's the boss theme that would play if today became a final battle?" },
  { text: "If today were a social-link rank-up, what stat improved?" },
  { text: "What's the tutorial popup you wish today came with?" },
  { text: "If today were an anime filler episode, what non-canon detour did you take?" },
  { text: "What's the power-up you clearly needed today but didn't get?" },
  { text: "If today were a JRPG random encounter, what enemy did you fight?" },
  { text: "What's the New Game Plus lesson you'd carry into tomorrow?" },
  { text: "If today had a difficulty setting, what was it set to?" },
  { text: "What's the cutscene you'd skip if you could replay today?" },

  // Famous quotes
  { text: "You can always edit a bad page. You can't edit a blank page.", attribution: "Jodi Picoult" },
  { text: "Writing is medicine. It is an appropriate antidote to injury. It is an appropriate companion for any difficult change.", attribution: "Julia Cameron" },
  { text: "We do not remember days, we remember moments.", attribution: "Cesare Pavese" },
  { text: "The life which is unexamined is not worth living.", attribution: "Socrates" },
  { text: "Fill your paper with the breathings of your heart.", attribution: "William Wordsworth" },
  { text: "Paper has more patience than people.", attribution: "Anne Frank" },
  { text: "We tell ourselves stories in order to live.", attribution: "Joan Didion" },
  { text: "There is no greater agony than bearing an untold story inside you.", attribution: "Maya Angelou" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", attribution: "Mark Twain" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", attribution: "Oscar Wilde" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", attribution: "Marcus Aurelius" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", attribution: "Rumi" },
  { text: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", attribution: "Toni Morrison" },
  { text: "Write it on your heart that every day is the best day in the year.", attribution: "Ralph Waldo Emerson" },
  { text: "It's not what you look at that matters, it's what you see.", attribution: "Henry David Thoreau" },
  { text: "You are never too old to set another goal or to dream a new dream.", attribution: "C.S. Lewis" },
  { text: "The only journey is the one within.", attribution: "Rainer Maria Rilke" },
  { text: "Owning our story and loving ourselves through that process is the bravest thing we'll ever do.", attribution: "Brené Brown" },
  { text: "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", attribution: "Sylvia Plath" },

  // Screen & game quotes
  { text: "Why do we fall, sir? So that we can learn to pick ourselves up.", attribution: "Alfred Pennyworth, Batman Begins" },
  { text: "It's not who you are underneath, it's what you do that defines you.", attribution: "Rachel Dawes, Batman Begins" },
  { text: "I used to be an adventurer like you, until I took an arrow in the knee.", attribution: "Guard dialogue, The Elder Scrolls V: Skyrim" },
  { text: "Despite everything, it's still you.", attribution: "Undertale" },
  { text: "Evil is evil. Lesser, greater, middling — makes no difference. The degree is arbitrary.", attribution: "Geralt of Rivia, The Witcher" },
  { text: "No. I am your father.", attribution: "Darth Vader, Star Wars: The Empire Strikes Back" },
  { text: "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.", attribution: "Yoda, Star Wars: The Phantom Menace" },
  { text: "One does not simply walk into Mordor.", attribution: "Boromir, The Lord of the Rings: The Fellowship of the Ring" },
  { text: "We've all got both light and dark inside us.", attribution: "Sirius Black, Harry Potter and the Order of the Phoenix" },
  { text: "There is no spoon.", attribution: "The Matrix" },
  { text: "Life was like a box of chocolates. You never know what you're gonna get.", attribution: "Forrest Gump" },
  { text: "Hope is a good thing, maybe the best of things, and no good thing ever dies.", attribution: "Andy Dufresne, The Shawshank Redemption" },
  { text: "Will our actions echo across the centuries? Will strangers hear our names long after we're gone, and wonder who we were?", attribution: "Achilles, Troy" },
  { text: "If they ever tell my story, let them say I walked with giants. Men rise and fall like the winter wheat, but these names will never die.", attribution: "Achilles, Troy" },
  { text: "Your mission, should you choose to accept it...", attribution: "Mission: Impossible" },
  { text: "I choose you, Pikachu!", attribution: "Ash Ketchum, Pokémon" },
  { text: "Gotta catch 'em all!", attribution: "Pokémon" },

  // Words from the greats — football
  { text: "Your love makes me strong, your hate makes me unstoppable.", attribution: "Cristiano Ronaldo" },
  { text: "The day you think there's no improvement to be made is a sad one for any player.", attribution: "Lionel Messi" },

  // Words from the greats — beyond the pitch
  { text: "Your time is limited, so don't waste it living someone else's life.", attribution: "Steve Jobs" },
  { text: "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.", attribution: "Muhammad Ali" },
  { text: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", attribution: "Kobe Bryant" },
  { text: "I really think a champion is defined not by their wins but by how they can recover when they fall.", attribution: "Serena Williams" },
  { text: "Being realistic is the most commonly traveled road to mediocrity.", attribution: "Will Smith" },

  // Celebrity Quotes
  { text: "Be yourself; everyone else is already taken.", attribution: "Oscar Wilde" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", attribution: "Robert Frost" },
  { text: "The way to get started is to quit talking and begin doing.", attribution: "Walt Disney" },
  { text: "Life is what happens when you're busy making other plans.", attribution: "John Lennon" },
  { text: "You only live once, but if you do it right, once is enough.", attribution: "Mae West" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", attribution: "Thomas Edison" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", attribution: "Winston Churchill" },
  { text: "Stay hungry, stay foolish.", attribution: "Steve Jobs" },
  { text: "The only way to do great work is to love what you do.", attribution: "Steve Jobs" },
  { text: "Whether you think you can or you think you can't, you're right.", attribution: "Henry Ford" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", attribution: "Eleanor Roosevelt" },
  { text: "Everything you've ever wanted is on the other side of fear.", attribution: "George Addair" },
  { text: "It always seems impossible until it's done.", attribution: "Nelson Mandela" },
  { text: "You can't use up creativity. The more you use, the more you have.", attribution: "Maya Angelou" },
  { text: "Nothing is impossible, the word itself says 'I'm possible!'", attribution: "Audrey Hepburn" },
  { text: "The best revenge is massive success.", attribution: "Frank Sinatra" },
  { text: "You define your own life. Don't let other people write your script.", attribution: "Oprah Winfrey" },
  { text: "Turn your wounds into wisdom.", attribution: "Oprah Winfrey" },
  { text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", attribution: "Jimmy Dean" },
  { text: "If you don't like the road you're walking, start paving another one.", attribution: "Dolly Parton" },

  // Sportsperson Quotes (General)
  { text: "It's not whether you get knocked down, it's whether you get up.", attribution: "Vince Lombardi" },
  { text: "I've failed over and over and over again in my life. And that is why I succeed.", attribution: "Michael Jordan" },
  { text: "Pain is temporary. Quitting lasts forever.", attribution: "Lance Armstrong" },
  { text: "Float like a butterfly, sting like a bee.", attribution: "Muhammad Ali" },
  { text: "It ain't over till it's over.", attribution: "Yogi Berra" },
  { text: "Champions aren't made in gyms. Champions are made from something they have deep inside them.", attribution: "Muhammad Ali" },
  { text: "The only way to prove that you're a good sport is to lose.", attribution: "Ernie Banks" },
  { text: "You can't put a limit on anything. The more you dream, the farther you get.", attribution: "Michael Phelps" },
  { text: "Talent wins games, but teamwork and intelligence win championships.", attribution: "Michael Jordan" },
  { text: "Somewhere behind the athlete you've become... is the little girl who fell in love with the game.", attribution: "Mia Hamm" },
  { text: "Don't count the days, make the days count.", attribution: "Muhammad Ali" },
  { text: "You were born to be a player. This moment is yours.", attribution: "Herb Brooks" },

  // Football (Soccer) Player Quotes
  { text: "I'm not a specialist in failure.", attribution: "José Mourinho" },
  { text: "Talent without working hard is nothing.", attribution: "Cristiano Ronaldo" },
  { text: "I am not a genius. I'm intelligent, and I work, work, work, and I try to figure things out.", attribution: "Lionel Messi" },
  { text: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", attribution: "Lionel Messi" },
  { text: "Football is like chess but without the dice.", attribution: "Lukas Podolski" },
  { text: "I've never wanted to be somebody. I just wanted to be myself.", attribution: "Zinedine Zidane" },
  { text: "Sometimes in football you have to score goals.", attribution: "Thierry Henry" },
  { text: "The day I stop learning, I'll die.", attribution: "Cristiano Ronaldo" },
  { text: "You can't win anything with kids.", attribution: "Alan Hansen, on Manchester United's 1995 squad" },
  { text: "I don't believe in luck. I believe in hard work.", attribution: "Cristiano Ronaldo" },
  { text: "It is not enough to be a good player, you also have to be a good teammate.", attribution: "Xavi Hernández" },
  { text: "Age is just a number. Mentality and body condition is the most important thing.", attribution: "Cristiano Ronaldo" },
  { text: "Football is a simple game based on the giving and taking of passes.", attribution: "Johan Cruyff" },
  { text: "I'm going to enjoy this moment, because I don't know if I'll ever have the chance again.", attribution: "Diego Maradona" },
  { text: "Every disadvantage has its advantage.", attribution: "Johan Cruyff" },
  { text: "Playing without the ball is what makes you a great player.", attribution: "Johan Cruyff" },
  { text: "I am like good wine. Every year that passes, I get better.", attribution: "Zlatan Ibrahimović" },
  { text: "Some people are afraid to say what they want, that's why they don't get what they want.", attribution: "Zlatan Ibrahimović" },
  { text: "A goal is a moment of magic in a night of hard work.", attribution: "Thierry Henry" },
  { text: "I don't have to prove myself to anybody. I just play the game and enjoy it.", attribution: "Ronaldinho" },
  { text: "Football is a matter of life and death — but even more important than that.", attribution: "Bill Shankly" },
  { text: "First touch, timing, that was my whole game.", attribution: "Ronaldinho" },
  { text: "You have to work for your dream, my dream is to win everything possible in football.", attribution: "Neymar Jr." },
  { text: "Excellence is not a singular act but a habit. You are what you repeatedly do.", attribution: "often quoted by Pep Guardiola in team talks, originally attributed to Aristotle" },
  { text: "I've never played for a draw in my life.", attribution: "Sir Bobby Charlton" },

  // Movie Quotes (with Characters)
  { text: "May the Force be with you.", attribution: "General Dodonna, Star Wars: A New Hope" },
  { text: "I'm gonna make him an offer he can't refuse.", attribution: "Vito Corleone, The Godfather" },
  { text: "Here's looking at you, kid.", attribution: "Rick Blaine, Casablanca" },
  { text: "You can't handle the truth!", attribution: "Colonel Nathan Jessup, A Few Good Men" },
  { text: "I'll be back.", attribution: "The Terminator, The Terminator" },
  { text: "Why so serious?", attribution: "The Joker, The Dark Knight" },
  { text: "Life is like a box of chocolates. You never know what you're gonna get.", attribution: "Forrest Gump, Forrest Gump" },
  { text: "There's no place like home.", attribution: "Dorothy Gale, The Wizard of Oz" },
  { text: "I feel the need — the need for speed.", attribution: "Maverick & Goose, Top Gun" },
  { text: "Houston, we have a problem.", attribution: "Jim Lovell, Apollo 13" },
  { text: "Just keep swimming.", attribution: "Dory, Finding Nemo" },
  { text: "To infinity and beyond!", attribution: "Buzz Lightyear, Toy Story" },
  { text: "Hasta la vista, baby.", attribution: "The Terminator, Terminator 2: Judgment Day" },
  { text: "You had me at hello.", attribution: "Dorothy Boyd, Jerry Maguire" },
  { text: "Not all those who wander are lost.", attribution: "Bilbo Baggins (letter, read by Gandalf), The Lord of the Rings: The Fellowship of the Ring" },
  { text: "With great power comes great responsibility.", attribution: "Uncle Ben, Spider-Man" },
  { text: "I am inevitable.", attribution: "Thanos, Avengers: Endgame" },
  { text: "Why do we fall? So we can learn to pick ourselves up.", attribution: "Thomas Wayne, Batman Begins" },
  { text: "Do, or do not. There is no try.", attribution: "Yoda, Star Wars: The Empire Strikes Back" },
  { text: "Carpe diem. Seize the day, boys.", attribution: "John Keating, Dead Poets Society" },
  { text: "After all, tomorrow is another day.", attribution: "Scarlett O'Hara, Gone with the Wind" },
  { text: "Get busy living, or get busy dying.", attribution: "Andy Dufresne, The Shawshank Redemption" },
  { text: "Every man dies, not every man really lives.", attribution: "William Wallace, Braveheart" },

  // Harry Potter Quotes
  { text: "It does not do to dwell on dreams and forget to live.", attribution: "Albus Dumbledore" },
  { text: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", attribution: "Albus Dumbledore" },
  { text: "It is our choices, Harry, that show what we truly are, far more than our abilities.", attribution: "Albus Dumbledore" },
  { text: "After all this time? / Always.", attribution: "Severus Snape, on his love for Lily Potter" },
  { text: "I solemnly swear that I am up to no good.", attribution: "Harry Potter" },
  { text: "Fear of a name only increases fear of the thing itself.", attribution: "Hermione Granger" },
  { text: "We've all got both light and dark inside us. What matters is the part we choose to act on.", attribution: "Sirius Black" },
  { text: "You're a wizard, Harry.", attribution: "Rubeus Hagrid" },
  { text: "Working hard is important, but there is something that matters even more: believing in yourself.", attribution: "Harry Potter" },
  { text: "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", attribution: "Albus Dumbledore" },

  // Star Wars Quotes
  { text: "I find your lack of faith disturbing.", attribution: "Darth Vader" },
  { text: "The Force will be with you, always.", attribution: "Obi-Wan Kenobi" },
  { text: "Never tell me the odds!", attribution: "Han Solo" },
  { text: "I am your father.", attribution: "Darth Vader" },
  { text: "Fear is the path to the dark side.", attribution: "Yoda" },
  { text: "This is the way.", attribution: "The Mandalorian" },
  { text: "I've got a bad feeling about this.", attribution: "Luke Skywalker, a recurring line across the saga" },
  { text: "Your eyes can deceive you; don't trust them.", attribution: "Obi-Wan Kenobi" },
  { text: "Great, kid. Don't get cocky.", attribution: "Han Solo" },
  { text: "So this is how liberty dies... with thunderous applause.", attribution: "Padmé Amidala, Revenge of the Sith" },

  // Video Game Quotes (General)
  { text: "War. War never changes.", attribution: "The Narrator, Fallout series" },
  { text: "It's dangerous to go alone! Take this.", attribution: "Old Man, The Legend of Zelda" },
  { text: "A man chooses, a slave obeys.", attribution: "Andrew Ryan, BioShock" },
  { text: "Would you kindly?", attribution: "Atlas, BioShock" },
  { text: "The cake is a lie.", attribution: "environmental message, Portal" },
  { text: "Stay awhile and listen.", attribution: "Deckard Cain, Diablo II" },
  { text: "Praise the sun!", attribution: "Solaire of Astora, Dark Souls" },
  { text: "You died.", attribution: "game-over text, Dark Souls" },
  { text: "It's-a me, Mario!", attribution: "Mario, Super Mario series" },
  { text: "Finish him!", attribution: "Announcer, Mortal Kombat" },
  { text: "Snake? Snake?! SNAAAAKE!", attribution: "Colonel Roy Campbell, Metal Gear Solid" },
  { text: "The right man in the wrong place can make all the difference in the world.", attribution: "G-Man, Half-Life 2" },
  { text: "Kept you waiting, huh?", attribution: "Big Boss, Metal Gear Solid" },
  { text: "I used to be an adventurer like you, then I took an arrow to the knee.", attribution: "Town Guard, The Elder Scrolls V: Skyrim" },
  { text: "Hey! Listen!", attribution: "Navi, The Legend of Zelda: Ocarina of Time" },
  { text: "War never changes, but the people who fight it, they do.", attribution: "The Narrator, Fallout series" },

  // GTA Quotes
  { text: "I used to rob banks. Yeah, that's right. What of it?", attribution: "Trevor Philips, GTA V" },
  { text: "A true friend stabs you in the front.", attribution: "Trevor Philips, GTA V" },
  { text: "The American Dream. All you need is a gun and a bag of money.", attribution: "Franklin Clinton, GTA V" },
  { text: "Ah, sh*t, here we go again.", attribution: "Carl \"CJ\" Johnson, GTA: San Andreas" },
  { text: "I'm not a hero. I've never claimed to be.", attribution: "Niko Bellic, GTA IV" },
  { text: "Everything I did, I did for my family.", attribution: "Niko Bellic, GTA IV" },

  // Disco Elysium Quotes
  { text: "You're an ancient reptile brain wrapped in a coat, wrapped in a tie.", attribution: "Kim Kitsuragi, on Harry" },
  { text: "I am the great communicator. The vox populi. I speak for all.", attribution: "Harry Du Bois" },
  { text: "This is not a failure. This is Revachol.", attribution: "the Ancient Reptilian Brain (in-game inner voice), paraphrased" },
  { text: "The world doesn't need you, cop. It just is.", attribution: "the Ancient Reptilian Brain, paraphrased" },

  // Mass Effect Quotes
  { text: "I should go.", attribution: "Commander Shepard, Mass Effect" },
  { text: "It's like the ground itself was giving birth to a Reaper.", attribution: "Commander Shepard, Mass Effect 2" },
  { text: "You have to give them hope.", attribution: "Anderson, Mass Effect" },
  { text: "Wake up, Commander Shepard. Wake up and smell the ashes.", attribution: "Sovereign, Mass Effect" },
  { text: "I'm Commander Shepard, and this is my favorite store on the Citadel.", attribution: "Commander Shepard, Mass Effect" },
  { text: "The Reapers are the ultimate expression of what we fear the most: mechanized annihilation.", attribution: "Commander Shepard, Mass Effect" },

  // Assassin's Creed Quotes
  { text: "Nothing is true, everything is permitted.", attribution: "Altaïr Ibn-La'Ahad" },
  { text: "We work in the dark to serve the light.", attribution: "Ezio Auditore da Firenze" },
  { text: "Requiescat in pace.", attribution: "Ezio Auditore da Firenze, said over the fallen" },
  { text: "It is not titles that maketh a man, but the man that maketh the title.", attribution: "Ezio Auditore da Firenze" },
  { text: "Where other men blindly follow the truth, remember — nothing is true.", attribution: "Altaïr Ibn-La'Ahad" },
  { text: "I have lived long enough to know that the men who come after us will be neither friends nor enemies. They will simply be men who believe things we don't.", attribution: "Ezio Auditore da Firenze" },
  { text: "You elude a plan by making none.", attribution: "Aveline de Grandpré" },
  { text: "History is written by those who win.", attribution: "Desmond Miles, paraphrased" },
  { text: "This is our covenant. We work in the dark to serve the light. We are assassins.", attribution: "Ezio Auditore da Firenze" },
  { text: "Grow strong, my friend, for even your best is yet to come.", attribution: "Adéwalé" },
  { text: "I was made to inflict pain. It is the only thing I am truly good at.", attribution: "Edward Kenway" },
  { text: "Money is only worth having if you spend it, or invest it, wisely.", attribution: "Edward Kenway" },
  { text: "The truth will always find its way to light.", attribution: "Connor Kenway" },
  { text: "Peace is not the absence of conflict, but the ability to cope with it.", attribution: "Connor Kenway" },
  { text: "I fear nothing. Everything is on the table. I am ready for whatever comes.", attribution: "Bayek of Siwa" },
  { text: "It is unwise to boast. Fate has a way of punishing pride.", attribution: "Bayek of Siwa" },
  { text: "Let go your regret, embrace what remains.", attribution: "Bayek of Siwa" },

  // Anime Quotes (General)
  { text: "A lesson without pain is meaningless.", attribution: "Edward Elric, Fullmetal Alchemist: Brotherhood" },
  { text: "I'll leave tomorrow's problems to tomorrow's me.", attribution: "Spike Spiegel, Cowboy Bebop" },
  { text: "The moment you think of giving up, think of the reason why you held on so long.", attribution: "Natsu Dragneel, Fairy Tail" },
  { text: "Fear is not evil. It tells you what your weakness is.", attribution: "Erza Scarlet, Fairy Tail" },
  { text: "People's lives don't end when they die, it ends when they lose faith.", attribution: "Itachi Uchiha, Naruto" },

  // Haikyuu Quotes
  { text: "You'll regret it if you don't try, so I recommend that you do.", attribution: "Koshi Sugawara" },
  { text: "The only ones who should look down on you are the ones who've climbed higher than you.", attribution: "Yui Michimiya" },
  { text: "As long as we're alive, there's meaning in living.", attribution: "Shoyo Hinata" },
  { text: "I don't dislike the idea of losing, but I hate quitting more.", attribution: "Kotaro Bokuto" },
  { text: "It's not over till you give up.", attribution: "Shoyo Hinata" },
  { text: "Flightless crows, huh? Let's see about that.", attribution: "Shoyo Hinata" },
  { text: "You can't win if you don't stand at the top.", attribution: "Tobio Kageyama" },
  { text: "There's no way I'll ever regret working hard.", attribution: "Tobio Kageyama" },

  // Jujutsu Kaisen Quotes
  { text: "Throughout Heaven and Earth, I alone am the honored one.", attribution: "Satoru Gojo" },
  { text: "I'm the strongest, so I have to be the one who fights.", attribution: "Satoru Gojo" },
  { text: "It's not about whether I'm scared or not. If I don't do it, no one else will.", attribution: "Yuji Itadori" },
  { text: "Even a broken clock is right twice a day, but a broken person is never right.", attribution: "Suguru Geto" },
  { text: "Sometimes it's kinder to lie.", attribution: "Nobara Kugisaki" },
  { text: "In this world, fear equates to malice, and malice always targets the weak.", attribution: "Yuji Itadori" },

  // Dragon Ball Z Quotes
  { text: "I am the hope of the universe. I am the answer to all living things that cry out for peace.", attribution: "Vegeta" },
  { text: "It's over 9000!", attribution: "Vegeta, about Goku's power level" },
  { text: "I am Son Goku, and I am not going to let you kill my friends!", attribution: "Son Goku" },
  { text: "I've always been stronger than you and I always will be.", attribution: "Vegeta" },
  { text: "The Earth has become far too small a stage for this battle.", attribution: "Piccolo" },

  // Solo Leveling Quotes
  { text: "Arise.", attribution: "Sung Jin-Woo" },
  { text: "The weak have no choice but to rely on the strong.", attribution: "Sung Jin-Woo" },
  { text: "From now on, I will do as I please.", attribution: "Sung Jin-Woo" },
  { text: "I'm not a hero. I'm just someone trying to survive.", attribution: "Sung Jin-Woo" },
  { text: "I don't remember choosing to be weak.", attribution: "Sung Jin-Woo" },

  // Attack on Titan Quotes
  { text: "If you win, you live. If you lose, you die. If you don't fight, you can't win.", attribution: "Eren Yeager" },
  { text: "The only thing we're allowed to do is believe that we won't regret the choice we made.", attribution: "Levi Ackerman" },
  { text: "This world is cruel... and also very beautiful.", attribution: "Mikasa Ackerman" },
  { text: "Even if my hopes are shattered, I will always... always struggle to survive.", attribution: "Eren Yeager" },
  { text: "There's a saying that the strong feed on the weak. That's just the way it is, and even weaklings understand that.", attribution: "Reiner Braun" },
  { text: "I want to see it. The outside world.", attribution: "Eren Yeager" },

  // One Piece Quotes
  { text: "If you don't take risks, you can't create a future.", attribution: "Monkey D. Luffy" },
  { text: "As long as people continue to pursue the meaning of freedom, these things will never cease to be.", attribution: "Gol D. Roger, paraphrased" },
  { text: "I don't want to conquer anything. I just think the guy with the most freedom in this whole ocean is the Pirate King.", attribution: "Monkey D. Luffy, paraphrased" },
  { text: "When do you think people die? When they are shot through the heart by a bullet? No — it's when they are forgotten.", attribution: "Dr. Hiluluk, paraphrased" },
  { text: "Being weak means nothing. Because there's always someone stronger.", attribution: "Roronoa Zoro" },
  { text: "I don't care if the whole world is against me, I'll protect my friends.", attribution: "Monkey D. Luffy, paraphrased sentiment repeated across the series" },
  { text: "Whatever you do, don't apologize for something you've decided to do.", attribution: "Roronoa Zoro" },
  { text: "A scar on the back is a swordsman's shame.", attribution: "Roronoa Zoro" },
  { text: "You gotta do what you gotta do, and I gotta do what I gotta do.", attribution: "Portgas D. Ace" },
  { text: "I'm gonna be King of the Pirates!", attribution: "Monkey D. Luffy" },
  { text: "It's not about who's strong and who's weak. It's about whether you get to see your friends again.", attribution: "Monkey D. Luffy, paraphrased" },
  { text: "Once you meet someone, you can never truly forget them. It just takes a while to remember.", attribution: "Nico Robin" },
  { text: "As long as I have friends around, I don't want anything else.", attribution: "Monkey D. Luffy" },
  { text: "If you can't protect your dream, don't even bother making it.", attribution: "Portgas D. Ace" },
  { text: "Power isn't determined by your size, but the size of your heart and dreams.", attribution: "Monkey D. Luffy" },
  { text: "I don't want to be the strongest. I just want to beat the strongest.", attribution: "Roronoa Zoro, paraphrased" },

  // Naruto Quotes
  { text: "It's not the face that makes someone a monster; it's the choices they make.", attribution: "Naruto Uzumaki" },
  { text: "Hard work is worthless for those that don't believe in themselves.", attribution: "Might Guy" },
  { text: "If you don't like your destiny, don't accept it.", attribution: "Naruto Uzumaki" },
  { text: "Being weak is nothing to be ashamed of... staying weak is.", attribution: "Might Guy" },
  { text: "I am not going to run away, I never go back on my word! That's my nindo, my ninja way!", attribution: "Naruto Uzumaki" },
  { text: "A shinobi must see through deception.", attribution: "Kakashi Hatake" },
  { text: "Those who break the rules are scum, but those who abandon their friends are worse than scum.", attribution: "Kakashi Hatake / Obito Uchiha" },
  { text: "The pain of being alone... I understand it, I've felt it too.", attribution: "Naruto Uzumaki, to Gaara" },
  { text: "It's true that if you don't take risks, you can't create a future.", attribution: "Naruto Uzumaki" },
  { text: "I know pain... and I won't run away.", attribution: "Naruto Uzumaki" },
  { text: "The world isn't perfect. But it's there for us, doing the best it can.", attribution: "Kakashi Hatake" },
  { text: "Naruto changed me. That idiot... he showed me a new path.", attribution: "Gaara, paraphrased" },
  { text: "A place you can return to... I think that's what a family is.", attribution: "Jiraiya, paraphrased" },
  { text: "The moment people come to know love, they carry the risk of hate.", attribution: "Nagato, paraphrased" },
  { text: "Talent isn't something you're born with, it's something you build through hard work.", attribution: "Might Guy, paraphrased" },

  // Game of Thrones Quotes
  { text: "Winter is coming.", attribution: "Ned Stark" },
  { text: "When you play the game of thrones, you win or you die.", attribution: "Cersei Lannister" },
  { text: "A Lannister always pays his debts.", attribution: "Tyrion Lannister" },
  { text: "The night is dark and full of terrors.", attribution: "Melisandre" },
  { text: "I drink and I know things.", attribution: "Tyrion Lannister" },
  { text: "Power resides where men believe it resides. It's a trick, a shadow on the wall.", attribution: "Varys" },
  { text: "Chaos isn't a pit. Chaos is a ladder.", attribution: "Petyr \"Littlefinger\" Baelish" },
  { text: "Never forget what you are. The rest of the world will not forget it.", attribution: "Tyrion Lannister" },
  { text: "A girl has no name.", attribution: "Arya Stark" },
  { text: "Valar Morghulis.", attribution: "Jaqen H'ghar, traditional Braavosi saying meaning \"all men must die\"" },
  { text: "I am not going to stop the wheel. I'm going to break the wheel.", attribution: "Daenerys Targaryen" },
  { text: "Fear cuts deeper than swords.", attribution: "Arya Stark, quoting Syrio Forel" },
  { text: "Dracarys.", attribution: "Daenerys Targaryen, commanding her dragons" },
  { text: "The things I do for love.", attribution: "Jaime Lannister" },
  { text: "Any man who must say 'I am the king' is no true king.", attribution: "Tywin Lannister" },
  { text: "The lone wolf dies, but the pack survives.", attribution: "Ned Stark / Sansa Stark" },
  { text: "There is only one god, and his name is Death. And there is only one thing we say to Death: not today.", attribution: "Syrio Forel" },
  { text: "The North remembers.", attribution: "recurring line among Northern characters" },
  { text: "What do we say to the God of Death?", attribution: "Syrio Forel" },
  { text: "Everything before the word 'but' is horsesh*t.", attribution: "Tyrion Lannister" },

  // The Boys Quotes
  { text: "I'm the only one who's honest about what I want.", attribution: "Homelander, paraphrased" },
  { text: "Diplomacy is just war by other means.", attribution: "Billy Butcher" },
  { text: "I ain't the hero. Never claimed to be.", attribution: "Billy Butcher" },
  { text: "Being a hero isn't about the cape, it's about what's underneath.", attribution: "Starlight, paraphrased" },
  { text: "You can't win against people who think they're always right.", attribution: "Hughie Campbell, paraphrased" },
  { text: "We're not friends. We're coworkers who happen to fight monsters together.", attribution: "Mother's Milk, paraphrased" },
  { text: "I've done things I'm not proud of, to protect the people I love.", attribution: "Billy Butcher, paraphrased" },
  { text: "Nobody's born a hero. There's no such thing.", attribution: "Starlight, paraphrased" },
  { text: "Power without accountability — that's the whole problem.", attribution: "Hughie Campbell, paraphrased" },
  { text: "The world doesn't need more heroes. It needs better people.", attribution: "Starlight, paraphrased" },

  // Stranger Things Quotes
  { text: "Friends don't lie.", attribution: "Eleven" },
  { text: "Mornings are for coffee and contemplation.", attribution: "Jim Hopper" },
  { text: "Once upon a time, there was a princess...", attribution: "Mike Wheeler, to Eleven" },
  { text: "I'm not a mistake!", attribution: "Eleven" },
  { text: "We're friends. And friends tell each other the truth.", attribution: "Max Mayfield, paraphrased" },
  { text: "Some doors need to stay shut.", attribution: "Jim Hopper, paraphrased" },
  { text: "You made me feel like a person again — like I wasn't a mistake.", attribution: "Eleven, to Mike" },
  { text: "I'm just a kid from Hawkins.", attribution: "Eddie Munson, paraphrased" },
  { text: "It's not a competition, but if it were, I'd be winning.", attribution: "Robin Buckley, paraphrased" },
  { text: "Being a nerd is deeply uncool... until it isn't.", attribution: "Dustin Henderson, paraphrased" },

  // BTS Quotes (Interviews & Speeches — not song lyrics)
  { text: "No matter who you are, where you're from, your skin color, gender identity: speak yourself.", attribution: "RM (Kim Namjoon), United Nations speech, 2018" },
  { text: "I have flaws and I'm scared, but I'm going to hug myself as I am.", attribution: "RM, paraphrased from his UN speech" },
  { text: "Life is a marathon, not a sprint. Slow and steady wins the race.", attribution: "RM" },
  { text: "You can't please everyone. Even the moon shrinks and grows.", attribution: "Suga (Min Yoongi), paraphrased common interview sentiment" },
  { text: "I want to be a person who gives strength to others, like the way music gave strength to me.", attribution: "Jimin, paraphrased" },
  { text: "Just as there's no dark without light, we can't be happy without sad moments.", attribution: "V (Kim Taehyung), paraphrased interview sentiment" },
  { text: "I believe effort makes you what you are.", attribution: "Jungkook, paraphrased from interviews" },
  { text: "It's okay to not be okay sometimes.", attribution: "J-Hope, paraphrased common interview sentiment" },
  { text: "The most important thing is to love yourself, not to be loved by someone else.", attribution: "Jin, paraphrased sentiment" },
  { text: "We are more than seven. With our fans, we are infinite.", attribution: "RM, paraphrased common sentiment expressed in interviews" },

  // Marvel Cinematic Universe Quotes
  { text: "I am Iron Man.", attribution: "Tony Stark, Iron Man / Avengers: Endgame" },
  { text: "I can do this all day.", attribution: "Steve Rogers (Captain America), Captain America: Civil War" },
  { text: "Whatever it takes.", attribution: "Tony Stark, Avengers: Endgame" },
  { text: "That's my secret, Captain. I'm always angry.", attribution: "Bruce Banner, The Avengers" },
  { text: "Avengers, assemble.", attribution: "Steve Rogers, Avengers: Endgame" },
  { text: "I love you 3000.", attribution: "Morgan Stark & Tony Stark, Avengers: Endgame" },
  { text: "Part of the journey is the end.", attribution: "Tony Stark, Avengers: Endgame" },
  { text: "In time, you will know what it's like to lose. To feel so desperately that you're right, yet to fail all the same.", attribution: "Thanos, Avengers: Infinity War" },
  { text: "Perfectly balanced, as all things should be.", attribution: "Thanos, Avengers: Infinity War" },
  { text: "Reality is often disappointing.", attribution: "Thanos, Avengers: Infinity War" },
  { text: "I am Groot.", attribution: "Groot, Guardians of the Galaxy" },
  { text: "We are Groot.", attribution: "Groot, Guardians of the Galaxy Vol. 2" },
  { text: "Dread it. Run from it. Destiny still arrives.", attribution: "Thanos, Avengers: Infinity War" },
  { text: "Even if you get killed, just walk it off!", attribution: "Tony Stark, The Avengers" },
  { text: "It's not about how much we lost. It's about how much we have left.", attribution: "Tony Stark, Avengers: Endgame" },
  { text: "Sometimes you gotta run before you can walk.", attribution: "Sam Wilson (Falcon), Captain America: The Winter Soldier" },
  { text: "Long live the king.", attribution: "Wakandan people, Black Panther" },
  { text: "Wakanda forever!", attribution: "T'Challa, Black Panther" },
  { text: "In this life, we are given one chance to be who we are.", attribution: "Erik Killmonger, Black Panther, paraphrased" },
  { text: "Death is not the end.", attribution: "Odin, Thor: Ragnarok, paraphrased" },
  { text: "I'm Mary Poppins, y'all!", attribution: "Wade Wilson (Deadpool), Deadpool 2" },
  { text: "You're not Superman, you know.", attribution: "Aunt May, Spider-Man: Homecoming, paraphrased" },
  { text: "This is the fight of our lives.", attribution: "Steve Rogers, Avengers: Endgame, paraphrased" },
  { text: "I can't control their fear, only my own.", attribution: "T'Challa, Black Panther, paraphrased" },
  { text: "The hardest choices require the strongest wills.", attribution: "Thanos, Avengers: Infinity War" },

  // Persona Series Quotes
  { text: "It's time to kick reality in the nuts!", attribution: "Ryuji Sakamoto, Persona 5" },
  { text: "Take your heart.", attribution: "recurring narrator line, Persona 5" },
  { text: "I am thou, thou art I.", attribution: "recurring Persona-awakening line across the series" },
  { text: "A prisoner who has grown accustomed to his chains will come to fear the freedom offered by a broken cell.", attribution: "Igor, Persona 5" },
  { text: "The unexamined life is not worth living, they say. But what about a life lived entirely in self-examination?", attribution: "Igor, paraphrased" },
  { text: "You are the one who will decide the fate of this world.", attribution: "Igor, paraphrased" },
  { text: "It's not about being perfect. It's about doing your best.", attribution: "Makoto Niijima, Persona 5, paraphrased" },
  { text: "Rules exist for a reason. If you don't like them, change them.", attribution: "Makoto Niijima, paraphrased" },
  { text: "I refuse to fade away without a fight!", attribution: "the Protagonist, Persona 5, paraphrased" },
  { text: "The bond you two share is proof you're not alone.", attribution: "recurring Social Link theme, Persona series, paraphrased" },
  { text: "It's not about winning or losing... it's about giving it your all.", attribution: "Persona 4, paraphrased" },
  { text: "Even if the world is against you, you have to keep going.", attribution: "Yu Narukami, Persona 4, paraphrased" },
  { text: "Whatever you decide, I'll support you.", attribution: "Chie Satonaka, Persona 4, paraphrased" },
  { text: "The truth isn't always kind.", attribution: "Naoto Shirogane, Persona 4, paraphrased" },

  // Elden Ring Quotes
  { text: "Rise, Tarnished, and let us walk a while.", attribution: "Melina, Elden Ring" },
  { text: "May you be guided by grace.", attribution: "recurring line throughout Elden Ring" },
  { text: "I am no Lord, merely a wretch, undeserving of the throne.", attribution: "the Tarnished, in-game framing, paraphrased" },
  { text: "Even in death, my honor remains.", attribution: "General Radahn, paraphrased" },
  { text: "We are all somebody's fool.", attribution: "Blaidd, paraphrased" },
  { text: "Let mine be a grand journey, though the road be lonely.", attribution: "Ranni the Witch, paraphrased" },
  { text: "The Golden Order shall be reestablished, or torn down entirely — the choice is yours.", attribution: "recurring in-game sentiment, Elden Ring, paraphrased" },

  // Red Dead Redemption Quotes
  { text: "I swear, I have not lied to you today.", attribution: "Arthur Morgan, Red Dead Redemption 2" },
  { text: "We're all just trying to survive out here, best we can.", attribution: "Arthur Morgan, paraphrased" },
  { text: "You can't help who you fall for, kid.", attribution: "Arthur Morgan, paraphrased" },
  { text: "I gave my whole life for this family, and look what it's brought me.", attribution: "Arthur Morgan, paraphrased" },
  { text: "Loyalty means something to me, John.", attribution: "Dutch van der Linde, paraphrased" },
  { text: "There's nothing quite as sad as watching a good man break bad.", attribution: "Arthur Morgan, paraphrased" },
  { text: "The world is changing... men like us, they got no place in it no more.", attribution: "Dutch van der Linde, paraphrased" },
  { text: "I gotta die of something.", attribution: "Arthur Morgan, Red Dead Redemption 2" },
  { text: "Feels like the whole world's coming to an end.", attribution: "John Marston, paraphrased" },
  { text: "Sometimes you gotta do wrong to survive.", attribution: "Sadie Adler, paraphrased" },

  // More K-pop Quotes (BLACKPINK, EXO, TWICE, Stray Kids — interviews only, no lyrics)
  { text: "We just want to show that girls can be strong and cool too.", attribution: "Jennie, BLACKPINK, paraphrased interview sentiment" },
  { text: "I think being different is what makes you special.", attribution: "Lisa, BLACKPINK, paraphrased" },
  { text: "Practice makes it look easy, but nothing about it was easy.", attribution: "Rosé, BLACKPINK, paraphrased" },
  { text: "I want to inspire people to believe in themselves.", attribution: "Jisoo, BLACKPINK, paraphrased" },
  { text: "We grow through the hard times, not the easy ones.", attribution: "Suho, EXO, paraphrased" },
  { text: "Every stage is a new challenge, and I love that.", attribution: "Baekhyun, EXO, paraphrased" },
  { text: "Our fans give us strength we didn't know we had.", attribution: "Chanyeol, EXO, paraphrased" },
  { text: "You have to trust the process, even when you can't see the result yet.", attribution: "Nayeon, TWICE, paraphrased" },
  { text: "We became stronger because we went through hardships together.", attribution: "Jihyo, TWICE, paraphrased" },
  { text: "I want to be someone who makes people smile.", attribution: "Momo, TWICE, paraphrased" },
  { text: "We're not afraid to be different — that's our strength.", attribution: "Bang Chan, Stray Kids, paraphrased" },
  { text: "Music is the one language we all understand.", attribution: "Han, Stray Kids, paraphrased" },
  { text: "Hard work always shows, even if it takes time.", attribution: "Felix, Stray Kids, paraphrased" },

  // Basketball Quotes
  { text: "I've never been afraid to fail.", attribution: "Kobe Bryant" },
  { text: "The moment you give up is the moment you let someone else win.", attribution: "Kobe Bryant, paraphrased" },
  { text: "Great things come from hard work and perseverance. No excuses.", attribution: "Kobe Bryant" },
  { text: "I can't relate to lazy people. We don't speak the same language.", attribution: "Kobe Bryant, paraphrased" },
  { text: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", attribution: "Kobe Bryant" },
  { text: "I'm not going to succumb to birthdays, injuries, or the aging process.", attribution: "LeBron James, paraphrased" },
  { text: "You have to be able to accept failure to get better.", attribution: "LeBron James, paraphrased" },
  { text: "Strive for greatness.", attribution: "LeBron James" },

  // Tennis Quotes
  { text: "It's a matter of discipline and inspiration — you need both to compete.", attribution: "Serena Williams, paraphrased" },
  { text: "A champion is defined not by their wins but by how they can recover when they fall.", attribution: "Serena Williams" },
  { text: "Pressure is a privilege.", attribution: "Billie Jean King" },

  // Daily Reflection — Write About Your Day
  { text: "What was the best part of today, even if it was small?" },
  { text: "What's one thing that challenged you today, and how did you handle it?" },
  { text: "Who did you interact with today that left an impression on you?" },
  { text: "What emotion did you feel most strongly today? What triggered it?" },
  { text: "Did today go the way you expected? What surprised you?" },
  { text: "What's something you learned today — about yourself, someone else, or the world?" },
  { text: "What's one thing you're grateful for from today?" },
  { text: "If you had to describe today in three words, what would they be?" },
  { text: "What's something you did today that your future self will thank you for?" },
  { text: "What drained your energy today, and what gave you energy?" },
  { text: "Did you keep a promise to yourself today? If not, why?" },
  { text: "What's one conversation from today you keep thinking about?" },
  { text: "How did your body feel today — energized, tired, tense, relaxed?" },
  { text: "What's something you want to remember about today, five years from now?" },
  { text: "Did you make any progress today toward something that matters to you?" },
  { text: "What's one thing you'd do differently if you could replay today?" },
  { text: "What made you laugh today?" },
  { text: "What's a small win from today that you might otherwise overlook?" },
  { text: "Who do you want to check in on tomorrow, based on today?" },
  { text: "What's the most honest thing you can say about how today felt?" },
  { text: "What's something today taught you about patience?" },
  { text: "Did anything today shift how you see a person or situation?" },

  // Morning Intentions
  { text: "What's one thing you want to accomplish today, no matter what?" },
  { text: "How do you want to feel by the end of today?" },
  { text: "What's one kind thing you can do for yourself today?" },
  { text: "What would make today feel successful?" },
  { text: "What's a thought you want to carry with you today?" },
  { text: "Who do you want to be today — patient, brave, curious, calm?" },
  { text: "What's the first thing you're looking forward to today?" },
  { text: "What's one thing you can let go of before the day even starts?" },

  // Evening Wind-Down
  { text: "What are three things that went right today?" },
  { text: "What's one thing you can forgive yourself for from today?" },
  { text: "What's still on your mind that you need to release before sleep?" },
  { text: "What's a moment from today you want to hold onto?" },
  { text: "What does your body need right now — rest, movement, food, quiet?" },
  { text: "What's one thing tomorrow-you will need from today-you?" },

  // Self-Reflection
  { text: "What is something you're proud of that you rarely tell others?" },
  { text: "What does \"success\" mean to you today, versus five years ago?" },
  { text: "What is a belief you held strongly that you've since changed your mind about?" },
  { text: "When do you feel most like yourself?" },
  { text: "What's a fear you've outgrown?" },
  { text: "What would you do differently if you knew no one was watching or judging?" },
  { text: "What's one thing you need to forgive yourself for?" },
  { text: "Describe a moment you felt truly proud of your own growth." },
  { text: "What parts of your personality did you inherit, and which are entirely your own?" },
  { text: "If you could tell your younger self one thing, what would it be?" },

  // Gratitude
  { text: "What are three small things that brought you joy this week?" },
  { text: "Who is someone that changed your life for the better, and how?" },
  { text: "What's a challenge you're grateful you went through?" },
  { text: "What does your body do for you every day that you take for granted?" },
  { text: "What's something ordinary in your life that you'd miss if it were gone?" },

  // Goals & Growth
  { text: "What's one goal you've been putting off, and why?" },
  { text: "What does your ideal day look like from morning to night?" },
  { text: "What habit would most improve your life if you kept it for a year?" },
  { text: "What is one skill you wish you had more courage to pursue?" },
  { text: "Where do you want to be, personally, in five years?" },
  { text: "What's a risk you've been afraid to take?" },
  { text: "What would you attempt if you knew you couldn't fail?" },
  { text: "What does \"enough\" look like for you — in money, time, or achievement?" },

  // Relationships
  { text: "Who in your life makes you feel most understood?" },
  { text: "What's a hard conversation you've been avoiding?" },
  { text: "What do you need more of from the people around you?" },
  { text: "How do you show love, and how do you like to receive it?" },
  { text: "What boundary do you need to set (or reinforce) in your life right now?" },

  // Emotional Processing
  { text: "What emotion do you find hardest to sit with, and why?" },
  { text: "Describe a recent moment of stress. What was your body telling you?" },
  { text: "What's something you're carrying that you haven't put into words yet?" },
  { text: "When was the last time you cried, and what was really underneath it?" },
  { text: "What does peace feel like in your body?" },

  // Creativity & Imagination
  { text: "If you could master any skill overnight, what would it be and what would you do with it?" },
  { text: "Describe your dream home in vivid detail." },
  { text: "If your life were a movie, what genre would it be right now?" },
  { text: "Write a letter to yourself ten years from now." },
  { text: "What's a story from your life that you'd want to tell your grandchildren?" },

  // Values & Purpose
  { text: "What do you stand for, even when it's inconvenient?" },
  { text: "What legacy do you want to leave behind?" },
  { text: "What does a meaningful life look like to you?" },
  { text: "What's something you'd fight for, no matter the cost?" },
  { text: "If you had unlimited resources, what problem in the world would you try to solve?" },

  // Present Moment
  { text: "What's on your mind right now that you haven't said out loud?" },
  { text: "What does today feel like, in one word — and why that word?" },
  { text: "What's something you need to let go of before tomorrow?" },
  { text: "What is one thing you can do today to be kinder to yourself?" },
  { text: "What are you avoiding right now, and what would happen if you faced it?" },

  // Weekly Check-In
  { text: "What was this week's biggest lesson?" },
  { text: "What's one thing you want to do differently next week?" },
  { text: "Who supported you this week, and did you thank them?" },
  { text: "What's a pattern you noticed in your mood or energy this week?" },
  { text: "What are you looking forward to next week?" },
  { text: "What's something you completed this week that you're proud of?" },
  { text: "What's a boundary you held (or wish you had held) this week?" },
  { text: "If this week had a headline, what would it say?" },

  // Identity & Change
  { text: "What's a version of yourself you're trying to grow into?" },
  { text: "What's something you used to care about that no longer matters to you?" },
  { text: "What does \"home\" mean to you right now?" },
  { text: "What's a label or expectation you're ready to shed?" },
  { text: "What would you do if you weren't afraid of being judged?" },
  { text: "What's a quality in others that you admire and want to build in yourself?" },

  // Small Joys & Comfort
  { text: "What's a smell, sound, or taste that instantly comforts you?" },
  { text: "What's something you own that has no monetary value but means everything to you?" },
  { text: "What's a place that feels like \"yours\"?" },
  { text: "What's a memory that always makes you smile?" },
  { text: "What's your favorite way to spend a completely free afternoon?" },

  // Overcoming Difficulty
  { text: "What's the hardest thing you've ever gotten through, and how did you do it?" },
  { text: "What would you tell someone going through what you went through?" },
  { text: "What's a setback that turned out to be a setup for something better?" },
  { text: "What does resilience look like for you, specifically?" },
  { text: "What's something difficult you're currently facing that you haven't said out loud yet?" },

  // Focus & Motivation
  { text: "What's one thing you're avoiding that, if done, would make everything else easier?" },
  { text: "What does \"showing up for yourself\" look like this week?" },
  { text: "What's a comfort zone you're ready to step outside of?" },
  { text: "If today was your last chance to make a change, what would you start?" },
  { text: "What's something you keep saying you'll do \"someday\"? Why not now?" },
  { text: "What's a fear that's quietly been running your decisions?" },
  { text: "What would you do this week if you weren't worried about failing?" },
  { text: "What's one small, uncomfortable action that would move you forward?" },
  { text: "What story are you telling yourself that might not be true?" },
  { text: "What does discipline look like for you on a hard day?" },

  // Connection & Community
  { text: "Who have you been meaning to reach out to?" },
  { text: "What's a way someone recently showed you they cared?" },
  { text: "What's a relationship in your life that needs more attention?" },
  { text: "Who do you feel safest being fully yourself around?" },
  { text: "What's something you wish someone would ask you about?" },

  // Looking Back, Looking Forward
  { text: "What would you tell yourself exactly one year ago?" },
  { text: "What's a chapter of your life you're ready to close?" },
  { text: "What's something you hope is different a year from now?" },
  { text: "What's a moment this year that changed how you see yourself?" },
  { text: "If you wrote a letter to next year's you, what would you want them to know?" },

  // Mindfulness & Awareness
  { text: "What sounds can you hear right now if you pause and listen?" },
  { text: "What's one thing your five senses are telling you in this moment?" },
  { text: "What thought keeps returning to your mind lately?" },
  { text: "When did you last feel fully present, with no distractions?" },
  { text: "What's a small ritual that helps you feel grounded?" },
  { text: "What would it look like to slow down today?" },

  // Big Questions
  { text: "What do you think happens after we die, and how does that shape how you live?" },
  { text: "If you could ask the universe one question, what would it be?" },
  { text: "What does \"enough\" feel like versus \"more\" feel like, in your life?" },
  { text: "What's a question you're afraid to ask yourself?" },
  { text: "What would you regret not doing if your life ended tomorrow?" },
  { text: "What does it mean to live a \"good\" life, in your own words?" },

  // A Few More
  { text: "What's a lesson you keep having to relearn?" },
  { text: "What's something you need to hear today, that you can say to yourself?" },
  { text: "What's a piece of advice you'd give to someone starting where you started?" },
  { text: "What does self-respect look like in practice for you?" },
  { text: "What's a moment you felt truly alive?" },
  { text: "What's something beautiful you noticed today that you'd otherwise forget?" },
  { text: "What's a question you wish someone would ask you more often?" },
  { text: "What would \"enough rest\" look like for you this week?" },
  { text: "What's one thing you can do to make tomorrow 1% better than today?" },
  { text: "What are you most looking forward to about your future self?" },
];

export function getRandomPrompt(exclude?: string): JournalPrompt {
  const pool = exclude ? JOURNAL_PROMPTS.filter((p) => p.text !== exclude) : JOURNAL_PROMPTS;
  return pool[Math.floor(Math.random() * pool.length)];
}
