export interface JournalPrompt {
  text: string;
  attribution?: string;
}

// A mix of direct prompts and short quotes to nudge someone who's staring
// at a blank page — shown one at a time above the composer, shuffle-able.
// Deliberately varied in register (plain daily check-in, more reflective/
// intellectual, random/silly, oddly specific, pop-culture flavored, and
// famous real quotes — literary, screen/game, and football) rather than
// one tone throughout — a blank-page nudge should sometimes be light,
// not always a therapy question. The screen/game/football quotes are
// kept short and clearly attributed (real, verifiable lines), the same
// bar as the literary quotes below.
export const JOURNAL_PROMPTS: JournalPrompt[] = [
  // Basic journaling questions
  { text: "How are you feeling right now?" },
  { text: "What's on your mind?" },
  { text: "What happened today?" },
  { text: "What's one word for today?" },
  { text: "What do you need right now?" },
  { text: "What's something you want to let go of?" },
  { text: "What's your intention for tomorrow?" },
  { text: "How did you sleep last night?" },
  { text: "What's something you're thinking about?" },
  { text: "What was the best part of your day?" },
  { text: "What was the hardest part of your day?" },
  { text: "What's something simple that made today better?" },

  // Plain, everyday
  { text: "What's the detail of what you accomplished today?" },
  { text: "What made you feel this way today?" },
  { text: "What made you feel excited today?" },
  { text: "What made you feel burned out today?" },
  { text: "What's one small thing that went right today?" },
  { text: "What are you looking forward to?" },
  { text: "What's something you'd like to remember about today?" },
  { text: "What's weighing on you right now?" },
  { text: "Who or what are you grateful for today?" },
  { text: "What's something you're proud of from today, even if it's small?" },
  { text: "What surprised you today?" },
  { text: "What's something you avoided today?" },
  { text: "How did you take care of yourself today?" },
  { text: "What conversation from today is still on your mind?" },
  { text: "What's something you learned about yourself today?" },
  { text: "What did you do today just for you?" },
  { text: "What's one thing you'd do differently if you could redo today?" },

  // More thoughtful / intellectual
  { text: "What belief do you hold today that you didn't a year ago?" },
  { text: "What's something you understand better now than you used to?" },
  { text: "What assumption did today quietly prove wrong?" },
  { text: "What would you tell yourself from exactly one year ago?" },
  { text: "What's a question about your own life you've been avoiding?" },
  { text: "If today were a chapter title in your autobiography, what would it be?" },
  { text: "What's a small discomfort you leaned into today instead of avoiding?" },
  { text: "What did today teach you that a textbook couldn't?" },
  { text: "What's something you did today purely out of habit — was it worth keeping?" },
  { text: "What's a belief you're still not sure you're allowed to have?" },
  { text: "If you could subtract one hour from today and add it to yesterday, would you?" },
  { text: "What's something you know intellectually but haven't fully accepted emotionally?" },
  { text: "What version of yourself were you performing today, if any?" },
  { text: "What's a contradiction you're currently living with?" },
  { text: "If today's choices were a data point, what pattern would they add to?" },
  { text: "What's something you did today that your future self will thank you for?" },
  { text: "What would you need to believe to feel differently about today?" },
  { text: "What's the smallest true thing you can say about today?" },
  { text: "If someone studied only today, what would they wrongly conclude about your life?" },

  // Random / fun
  { text: "If today had a soundtrack, what's the one song stuck in your head?" },
  { text: "What's the weirdest thing that happened today?" },
  { text: "Describe today using exactly three words." },
  { text: "What snack (or meal) saved today?" },
  { text: "If today were a weather forecast, what would it say?" },
  { text: "What's a completely useless fact you know, and why do you still know it?" },
  { text: "If your day were a movie genre, which one, and why?" },
  { text: "What made you laugh today, even just a little?" },
  { text: "If you could replay one hour from today, which one would you pick?" },
  { text: "If today were a flavor, what would it taste like?" },
  { text: "What's a smell that instantly time-traveled you somewhere today?" },
  { text: "If today had a warning label, what would it say?" },
  { text: "What's the most chaotic five minutes of your day?" },
  { text: "If your energy today were a battery percentage, what was it at 3pm?" },
  { text: "What's a word you overused today, out loud or in your head?" },
  { text: "If today were a plant, what kind would it be and why?" },
  { text: "What's the dumbest thing you thought about for way too long today?" },
  { text: "If today came with a soundtrack cue, what instrument would it be?" },
  { text: "What's one thing today that made zero sense?" },
  { text: "If you had to sell today on a shopping channel, what's your pitch?" },
  { text: "What color was today, and why?" },

  // Oddly specific / niche
  { text: "What's a smell that took you somewhere else today?" },
  { text: "If your day had a one-star review, what would it complain about?" },
  { text: "What's a rule — even a tiny one — you broke today?" },
  { text: "Name a sound from today you could pick out blindfolded." },
  { text: "What almost happened today, but didn't?" },
  { text: "What's something you did today your childhood self would be baffled by?" },
  { text: "What's the most 'you' thing you did today?" },
  { text: "Name a texture that stuck with you today." },
  { text: "What's something you almost said out loud but didn't?" },
  { text: "What's a tiny rebellion you committed today?" },
  { text: "What's something you only noticed because you were paying attention?" },
  { text: "What's a decision today you made in under five seconds?" },
  { text: "What object did you touch the most today, and what does that say?" },
  { text: "What's a habit you almost broke today but didn't?" },
  { text: "If today left a stain, what color would it be?" },

  // Pop-culture flavored
  { text: "If today were an episode title, what would it be called?" },
  { text: "Which sitcom character's energy did you have today?" },
  { text: "If you had a training montage today, what song would play?" },
  { text: "What villain-origin-story moment did today almost give you?" },
  { text: "Which fictional universe would today's events fit into best?" },
  { text: "If you had a superhero power today, what small problem would you have used it on?" },
  { text: "What's the meme that best sums up today?" },
  { text: "If today were a video game level, what was the boss fight?" },
  { text: "Which fictional character would've handled today better than you?" },
  { text: "What's a plot-armor moment from today — something that should've gone wrong but didn't?" },
  { text: "If today unlocked an achievement, what would it be called?" },
  { text: "If today were a season finale cliffhanger, what question got left unanswered?" },
  { text: "What's the opening line if today were a true-crime documentary?" },
  { text: "If today were a reality TV confessional, what would you say to the camera?" },
  { text: "Which fictional sidekick would've had the most commentary on your day?" },

  // Video games & interactive worlds
  { text: "If today were a Skyrim quest, what would the objective marker say?" },
  { text: "What today would count as taking an arrow in the knee?" },
  { text: "If today were a Disco Elysium skill check, which skill would've failed you?" },
  { text: "What internal voice argued with you the loudest today?" },
  { text: "If today were a GTA wanted level, how many stars would you be at right now?" },
  { text: "What's the side quest you got distracted by instead of today's main story?" },
  { text: "If today had a loading-screen tip, what would it say?" },
  { text: "What would your character sheet's 'notable trait' be after today?" },
  { text: "If today were a save file, what would you name the checkpoint?" },
  { text: "What's a debuff you were clearly under today?" },

  // Movies — MCU, DC & beyond
  { text: "If today were an MCU post-credits scene, what's the twist?" },
  { text: "Which superhero's day off did today resemble most?" },
  { text: "If today were a Batman origin-story beat, what happened in the alley?" },
  { text: "What was your 'I am inevitable' moment today — the thing you couldn't stop?" },
  { text: "Which villain monologue best explains your mood today?" },
  { text: "If today needed a post-credits scene, what would it tease?" },
  { text: "What's the training-montage moment from today?" },
  { text: "If today were a movie trailer, what's the one line that would sell it?" },
  { text: "What's the plot hole in today that nobody's going to question?" },

  // From the pitch — football flavored
  { text: "If today were a match, what's the final scoreline?" },
  { text: "What was your Messi moment today — small, quiet, but decisive?" },
  { text: "What was your Ronaldo moment today — loud, unmissable, celebrated?" },
  { text: "If today went to penalties, who would you trust to take the kick?" },
  { text: "What's the stoppage-time goal of your day — the thing that saved it at the last second?" },
  { text: "If today were a post-match interview, what's the one line you'd give reporters?" },
  { text: "What red card would you show today, if you could?" },
  { text: "If your day were a highlight reel, what's the one clip everyone would replay?" },

  // More mainstream games
  { text: "If today were a Dark Souls boss fight, how many tries did it take?" },
  { text: "What was today's 'Praise the Sun' moment — a small win worth celebrating?" },
  { text: "If today were a Zelda dungeon, what was the boss key you needed?" },
  { text: "What's the crafting recipe for today — what ingredients made it what it was?" },
  { text: "If today were a Portal test chamber, what was the trick you didn't see coming?" },
  { text: "What quest marker popped up out of nowhere today?" },
  { text: "If today were an RPG dialogue tree, which option did you almost pick but didn't?" },
  { text: "What's the respawn point you'd set today, if you could redo the rest?" },
  { text: "If today were a battle royale, what round did you get eliminated in?" },
  { text: "What's the easter egg from today — something small only you noticed?" },
  { text: "If today were an open-world map, what was still fogged over by the end?" },
  { text: "What NPC-brained moment did you have today — repeating the same line on a loop?" },

  // More movies
  { text: "If today were a Star Wars scene, were you closer to the light side or the dark side?" },
  { text: "What was your 'carrying the ring' moment today — the thing you couldn't put down?" },
  { text: "If today were a heist movie, what was the plan that almost went wrong?" },
  { text: "What's the twist ending if today were a thriller?" },
  { text: "If today were narrated like a nature documentary, what would the narrator say about you?" },
  { text: "What's the one scene from today you'd cut in the edit?" },
  { text: "If today were a Pixar movie, what's the emotional gut-punch moment?" },
  { text: "What's the soundtrack-swell moment from today — when it would've felt cinematic?" },
  { text: "If today were a courtroom drama, what would you plead guilty to?" },
  { text: "What's the sequel hook from today — something left unresolved?" },
  { text: "If today got a director's cut, what deleted scene would you add back in?" },

  // Celebrity-flavored
  { text: "Whose work ethic did today's grind remind you of?" },
  { text: "If a camera crew followed you today for a documentary, what would the trailer tease?" },
  { text: "What's the red-carpet-ready moment from today, if any?" },
  { text: "If you had to give an acceptance speech for today, who would you thank first?" },
  { text: "What's the comeback story arc your day is quietly building toward?" },
  { text: "If today were a magazine cover, what's the headline?" },

  // Anime & more games
  { text: "If today were a Jujutsu Kaisen domain expansion, what would yours be called?" },
  { text: "What was your Gojo-tier flex moment today, however small?" },
  { text: "If today were a One Piece arc, what island did you wash up on?" },
  { text: "What's the bounty you'd put on today's chaos?" },
  { text: "If today leveled you up like Solo Leveling, what stat went up?" },
  { text: "What was your 'it's over 9000' moment today — something that spiked out of nowhere?" },
  { text: "If today were a Pokémon battle, what move did you use, and was it super effective?" },
  { text: "What starter would today's mood evolve into?" },
  { text: "If today were a Mass Effect dialogue wheel, which option did you pick — paragon or renegade?" },
  { text: "What's the loyalty mission you completed for someone today?" },

  // More movies — Troy & Mission Impossible
  { text: "If today were a Mission: Impossible briefing, what was your mission, should you have chosen to accept it?" },
  { text: "What self-destructed after five seconds today, metaphorically speaking?" },
  { text: "If today were an epic like Troy, what would the opening narration say about you?" },
  { text: "What's the thing you'd want people to remember about today, years from now?" },

  // Niche references
  { text: "If today needed a skill check like in Disco Elysium, what would you have rolled for and failed?" },
  { text: "What's the boss theme that would play if today became a final battle?" },
  { text: "If today were a social-link rank-up, what stat improved?" },
  { text: "What's the tutorial popup you wish today came with?" },
  { text: "If today were an anime filler episode, what non-canon detour did you take?" },
  { text: "What's the power-up you clearly needed today but didn't get?" },
  { text: "If today were a JRPG random encounter, what enemy did you fight?" },
  { text: "What's the New Game Plus lesson you'd carry into tomorrow?" },
  { text: "If today had a difficulty setting, what was it set to?" },
  { text: "What's the cutscene you'd skip if you could replay today?" },

  // Famous quotes
  { text: "You can always edit a bad page. You can't edit a blank page.", attribution: "Jodi Picoult" },
  { text: "Writing is medicine. It is an appropriate antidote to injury. It is an appropriate companion for any difficult change.", attribution: "Julia Cameron" },
  { text: "We do not remember days, we remember moments.", attribution: "Cesare Pavese" },
  { text: "The life which is unexamined is not worth living.", attribution: "Socrates" },
  { text: "Fill your paper with the breathings of your heart.", attribution: "William Wordsworth" },
  { text: "Paper has more patience than people.", attribution: "Anne Frank" },
  { text: "We tell ourselves stories in order to live.", attribution: "Joan Didion" },
  { text: "There is no greater agony than bearing an untold story inside you.", attribution: "Maya Angelou" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", attribution: "Mark Twain" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", attribution: "Oscar Wilde" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", attribution: "Marcus Aurelius" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", attribution: "Rumi" },
  { text: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", attribution: "Toni Morrison" },
  { text: "Write it on your heart that every day is the best day in the year.", attribution: "Ralph Waldo Emerson" },
  { text: "It's not what you look at that matters, it's what you see.", attribution: "Henry David Thoreau" },
  { text: "You are never too old to set another goal or to dream a new dream.", attribution: "C.S. Lewis" },
  { text: "The only journey is the one within.", attribution: "Rainer Maria Rilke" },
  { text: "Owning our story and loving ourselves through that process is the bravest thing we'll ever do.", attribution: "Brené Brown" },
  { text: "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", attribution: "Sylvia Plath" },

  // Screen & game quotes
  { text: "I can do this all day.", attribution: "Steve Rogers, Captain America: Civil War" },
  { text: "I am Iron Man.", attribution: "Tony Stark, Iron Man" },
  { text: "I am inevitable.", attribution: "Thanos, Avengers: Endgame" },
  { text: "Why do we fall, sir? So that we can learn to pick ourselves up.", attribution: "Alfred Pennyworth, Batman Begins" },
  { text: "It's not who you are underneath, it's what you do that defines you.", attribution: "Rachel Dawes, Batman Begins" },
  { text: "With great power comes great responsibility.", attribution: "Uncle Ben, Spider-Man" },
  { text: "I used to be an adventurer like you, until I took an arrow in the knee.", attribution: "Guard dialogue, The Elder Scrolls V: Skyrim" },
  { text: "The cake is a lie.", attribution: "GLaDOS, Portal" },
  { text: "Praise the Sun!", attribution: "Solaire of Astora, Dark Souls" },
  { text: "It's dangerous to go alone! Take this.", attribution: "The Legend of Zelda" },
  { text: "Despite everything, it's still you.", attribution: "Undertale" },
  { text: "Evil is evil. Lesser, greater, middling — makes no difference. The degree is arbitrary.", attribution: "Geralt of Rivia, The Witcher" },
  { text: "May the Force be with you.", attribution: "Star Wars" },
  { text: "No. I am your father.", attribution: "Darth Vader, Star Wars: The Empire Strikes Back" },
  { text: "Do. Or do not. There is no try.", attribution: "Yoda, Star Wars: The Empire Strikes Back" },
  { text: "I find your lack of faith disturbing.", attribution: "Darth Vader, Star Wars: A New Hope" },
  { text: "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.", attribution: "Yoda, Star Wars: The Phantom Menace" },
  { text: "Never tell me the odds.", attribution: "Han Solo, Star Wars: The Empire Strikes Back" },
  { text: "This is the way.", attribution: "The Mandalorian" },
  { text: "One does not simply walk into Mordor.", attribution: "Boromir, The Lord of the Rings: The Fellowship of the Ring" },
  { text: "Not all those who wander are lost.", attribution: "J.R.R. Tolkien, The Lord of the Rings" },
  { text: "I solemnly swear that I am up to no good.", attribution: "Harry Potter" },
  { text: "It does not do to dwell on dreams and forget to live.", attribution: "Albus Dumbledore, Harry Potter and the Sorcerer's Stone" },
  { text: "It is our choices, Harry, that show what we truly are, far more than our abilities.", attribution: "Albus Dumbledore, Harry Potter and the Chamber of Secrets" },
  { text: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", attribution: "Albus Dumbledore, Harry Potter and the Prisoner of Azkaban" },
  { text: "We've all got both light and dark inside us.", attribution: "Sirius Black, Harry Potter and the Order of the Phoenix" },
  { text: "There is no spoon.", attribution: "The Matrix" },
  { text: "Life was like a box of chocolates. You never know what you're gonna get.", attribution: "Forrest Gump" },
  { text: "Get busy living, or get busy dying.", attribution: "Andy Dufresne, The Shawshank Redemption" },
  { text: "Hope is a good thing, maybe the best of things, and no good thing ever dies.", attribution: "Andy Dufresne, The Shawshank Redemption" },
  { text: "Will our actions echo across the centuries? Will strangers hear our names long after we're gone, and wonder who we were?", attribution: "Achilles, Troy" },
  { text: "If they ever tell my story, let them say I walked with giants. Men rise and fall like the winter wheat, but these names will never die.", attribution: "Achilles, Troy" },
  { text: "Your mission, should you choose to accept it...", attribution: "Mission: Impossible" },
  { text: "I should go.", attribution: "Commander Shepard, Mass Effect" },
  { text: "I'm gonna be King of the Pirates!", attribution: "Monkey D. Luffy, One Piece" },
  { text: "If you don't take risks, you can't create a future!", attribution: "Monkey D. Luffy, One Piece" },
  { text: "Throughout Heaven and Earth, I alone am the honored one.", attribution: "Gojo Satoru, Jujutsu Kaisen" },
  { text: "Arise.", attribution: "Sung Jinwoo, Solo Leveling" },
  { text: "It's over 9000!", attribution: "Vegeta, Dragon Ball Z" },
  { text: "I choose you, Pikachu!", attribution: "Ash Ketchum, Pokémon" },
  { text: "Gotta catch 'em all!", attribution: "Pokémon" },

  // Words from the greats — football
  { text: "Talent without working hard is nothing.", attribution: "Cristiano Ronaldo" },
  { text: "Your love makes me strong, your hate makes me unstoppable.", attribution: "Cristiano Ronaldo" },
  { text: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", attribution: "Lionel Messi" },
  { text: "The day you think there's no improvement to be made is a sad one for any player.", attribution: "Lionel Messi" },

  // Words from the greats — beyond the pitch
  { text: "Your time is limited, so don't waste it living someone else's life.", attribution: "Steve Jobs" },
  { text: "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.", attribution: "Muhammad Ali" },
  { text: "Float like a butterfly, sting like a bee.", attribution: "Muhammad Ali" },
  { text: "I've failed over and over and over again in my life and that is why I succeed.", attribution: "Michael Jordan" },
  { text: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", attribution: "Kobe Bryant" },
  { text: "I really think a champion is defined not by their wins but by how they can recover when they fall.", attribution: "Serena Williams" },
  { text: "The way to get started is to quit talking and begin doing.", attribution: "Walt Disney" },
  { text: "Being realistic is the most commonly traveled road to mediocrity.", attribution: "Will Smith" },
];

export function getRandomPrompt(exclude?: string): JournalPrompt {
  const pool = exclude ? JOURNAL_PROMPTS.filter((p) => p.text !== exclude) : JOURNAL_PROMPTS;
  return pool[Math.floor(Math.random() * pool.length)];
}
